# Net Charge of Peptides

In [ ]:
#install.packages("Peptides", dependencies=TRUE)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependency ‘Rcpp’

In [ ]:
#install.packages("reticulate")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘RcppTOML’, ‘here’, ‘png’

In [ ]:
library("Peptides")

In [ ]:
library("reticulate")

In [ ]:
pep_data <- read.csv("peptide.csv")

pep_data

     Category Sequence
1    toxin    ACSGRGSRCPPQCCMGLTCGREYPPRC
2    toxin    CGPCFTKDPETEKKCATCCGGIGRCFGPQCLCNRGY
3    toxin    MSDINATRLPHLVRYPPYVGDGTDLTLNRGEK
4    toxin    QKELVVTATTTCCGYNPMTSCPRCMCDSSCNKKKP
5    toxin    CCPFPMCYQVPHCPCC
6    toxin    CTENGDVCDPENHNCCSGSCLDDEDPPVCGF
7    toxin    CKGRGGACTKAMFICCSGSCNRGRC
8    toxin    SCDSEFSSEFCEQPEERICSCSTHVCCHLSSSKRDQCMTWNRCLSAQTGN
9    toxin    VATSEQFNKTFIELVIVVD
10   toxin    DGVCSNRRQCNKEVCGSSYDVAIVGA
11   toxin    SGSTCTCFTSTNCQGSCECLSPPGCYCSNNGIRQRGCSCTCPGT
12   toxin    ASNHENSKGSTRNGRHTIQECCMDPVCRLIIEKFGKDFAAALDFRRLPYR
13   toxin    SDGRDDEAKDERPDMYKSKRDGRCCHPACAKHFNCGR
14   toxin    LKCKNKVVPFLKCKNKVVPFLCYKMTLKKVTPKIKRG
15   toxin    KQCTSNMCSADCSPGCCIIDKLEWCTCDC
16   toxin    GKCGDINAPCKAECDCCGYTTCDCYWGN
17   toxin    TCSPAGEVCTSKSPCCTGFLCSHIGGMCHH
18   toxin    ACVGENKQCADWAGPHCCDGYYCTCRYFPKCICRNNN
19   toxin    DAADVKPVARTNEGPGRDPAPCCQHPIETCC
20   toxin    CYGFGEACLVLYTDCCGYCVLAVCL
21   toxin    TLLNILRDGDNCCIDKQGCCPW
22   toxin    DCQALWDYCPVPLLSSGDCCYGLICGPFVCIGW
23   toxin    CLSGGEVCDFLFPKCCNYCILLFCS
24   toxin    GCCSRPPCIANNPDIC
25   toxin    DGCPPHPVPGMHPCMCTNTC
26   toxin    TCVMFGSMCDKEEHSICCYECDYKKGICV
27   toxin    GDEEYSKMAAEREREAGRLDLSKFP
28   toxin    CTPAGKACDATATCCVLFCNLVTNKCQVPRFP
29   toxin    GVDKEGCRYLLGACTIDDDCCLHLGCNKKYGHCGWDGTF
30   toxin    AAAISCVGSKECLPKCKAQGCKSGKCMNKKCKCYC
⋮    ⋮        ⋮
3835 non-t    MAPCSCKSCGTSCAGSCTSCSCGSCSH
3836 non-t    FIGTALGIASAIPAIVKLFK
3837 non-t    HSDGTFTSELSRLRDSARLQRLLQGLV
3838 non-t    GKAFDDGAFTGIREINLSINKETAIGD
3839 non-t    YVGQRLCGSQLVDTLYSVCKHRGFYRPSEGIVDQCCTNICSRNQLLTYCN
3840 non-t    MMNLLSGWFYILMFYIGVNFPYWMGWSTTAFGFYTP
3841 non-t    NVSLITAFDNLDLSRKGAYYLYYLLSERLKRGGVPVHVNRA
3842 non-t    MCIFFFFKKLFFVEINVCLSFFFLFYFIFVLFFAAEVRNNDF
3843 non-t    GCPRILMRCKQDSDCLAGCVCGPNGFCGSP
3844 non-t    MRQKVTLACVQCASRNYTAAKQIRRLGERLMANKFCSTCNKHTIHRETK
3845 non-t    GKTKGVTSGLIAFPRL
3846 non-t    MEPAIVLIISVGAALVAVTGYGIYTAFGPPSRELSDPFEDHED
3847 non-t    MTTFNNLPSIFVPLVGLVFPAIAMASLFLHIQKNKIF
3848 non-t    MSDKPDISEVTSFDKTKLKKTETQEKNPLPSKETIEQEKAAATS
3849 non-t    MNLEIVFQLTALLFVVAAGPLVIVLLASRGGNL
3850 non-t    MKCGRKRRRRRRHACKRKKRACKQRSSTIVRAHLVHRRRAARRCP
3851 non-t    MVILLHKFQLDELIYIVLAQGYHQIPEYVRFQFPLYAHKDIHLYMKKLVL
3852 non-t    MKVRASVKKMCDNCRVIKRKGKVMVICSNAKHKQRQG
3853 non-t    MLKYIYMHLSHKYNHILFTYNMRIYLIKRNHMLFTHMFTTYAYIM
3854 non-t    SHQDCYEALHKCMASHSKPFSCSMKFHMCLQQQ
3855 non-t    MKNSKDILNNAIEEVSEKELMEVAGGKRGSGWIATITDDCPNSVFVCC
3856 non-t    MKRTYQPSVTRRKRTHGFRVRMKTAGGRKVINARRAKGRKRLAI
3857 non-t    MKIRNSLRSLRNRHRDNRLVRRKGRVYIINKTNRRFKARQG
3858 non-t    METATVLIVFIASLLLGVTGYSVYTAFGPNSKDLRDPFEDHED
3859 non-t    GLWSKIKEAGKAAVKAAGKAALGAVANSV
3860 non-t    EDDHHHHHHHHHGVGGGGGGGGGG
3861 non-t    MTTNTQYIYPIFTVRWLAVHALAVPTVFFLGSISAMQFIQR
3862 non-t    GILDVAKTLVGKLRNVLGI
3863 non-t    MKVLSSLASAKTRYPDCQVVRRRGRVYVICKSNPRFKAVQGRKKRR
3864 non-t    MKSIDLTILSLKRKGIRTEKVLKNQNPDRLSHMTDKNAQPKSKEKEE

In [ ]:
n_c_list = list()

for (row in 1:nrow(pep_data)){
  seq <- pep_data[row, "Sequence"]
  #print(seq)
  n_c <- charge(seq,pH= 7, pKscale= "EMBOSS")
  n_c_list <- c(n_c_list, n_c)
}

In [ ]:
length(n_c_list)

[1] 3864

In [ ]:
n_c_list

[[1]]
[1] 2.792425

[[2]]
[1] 1.7327

[[3]]
[1] 0.2180307

[[4]]
[1] 2.792594

[[5]]
[1] 0.03143338

[[6]]
[1] -7.960032

[[7]]
[1] 4.791648

[[8]]
[1] -2.781121

[[9]]
[1] -2.020956

[[10]]
[1] -0.1141795

[[11]]
[1] 0.6698176

[[12]]
[1] 3.369305

[[13]]
[1] 1.339621

[[14]]
[1] 11.88139

[[15]]
[1] -2.266011

[[16]]
[1] -2.236945

[[17]]
[1] 0.5138321

[[18]]
[1] 0.9710606

[[19]]
[1] -1.901735

[[20]]
[1] -2.208356

[[21]]
[1] -1.1445

[[22]]
[1] -3.207232

[[23]]
[1] -1.206927

[[24]]
[1] -0.1459286

[[25]]
[1] -0.6654193

[[26]]
[1] -1.964476

[[27]]
[1] -2.017351

[[28]]
[1] 1.792448

[[29]]
[1] -1.72436

[[30]]
[1] 6.729863

[[31]]
[1] -3.204391

[[32]]
[1] 2.731287

[[33]]
[1] 4.035197

[[34]]
[1] -6.957546

[[35]]
[1] 2.824502

[[36]]
[1] -4.017825

[[37]]
[1] -5.961451

[[38]]
[1] -0.724992

[[39]]
[1] 6.270736

[[40]]
[1] -7.201873

[[41]]
[1] 1.033805

[[42]]
[1] 3.272315

[[43]]
[1] -2.021425

[[44]]
[1] -1.081939

[[45]]
[1] 4.092106

[[46]]
[1] 4.093211

[[47]]
[1] -3.080523

[[48]]
[1] -2.662908

[[49]]
[1] 2.794639

[[50]]
[1] 1.765865

[[51]]
[1] -2.016558

[[52]]
[1] -0.6948271

[[53]]
[1] -12.1931

[[54]]
[1] 2.093372

[[55]]
[1] 2.730646

[[56]]
[1] 6.336448

[[57]]
[1] 0.8529445

[[58]]
[1] 0.7948007

[[59]]
[1] -5.543084

[[60]]
[1] -1.206769

[[61]]
[1] 1.735682

[[62]]
[1] -2.205673

[[63]]
[1] 2.033153

[[64]]
[1] -0.2063199

[[65]]
[1] -0.02331488

[[66]]
[1] -0.4861679

[[67]]
[1] 3.881865

[[68]]
[1] -3.205975

[[69]]
[1] -2.146255

[[70]]
[1] 4.095891

[[71]]
[1] -0.9663689

[[72]]
[1] -5.962877

[[73]]
[1] -0.1440392

[[74]]
[1] 1.21132

[[75]]
[1] 1.794023

[[76]]
[1] -0.9069546

[[77]]
[1] -5.781248

[[78]]
[1] -1.962737

[[79]]
[1] 0.4831787

[[80]]
[1] -0.5425004

[[81]]
[1] 4.791489

[[82]]
[1] 0.03333592

[[83]]
[1] 0.4522169

[[84]]
[1] 1.454567

[[85]]
[1] -2.08178

[[86]]
[1] 0.3388386

[[87]]
[1] -1.146719

[[88]]
[1] 3.397315

[[89]]
[1] 0.03692687

[[90]]
[1] 4.792283

[[91]]
[1] -1.082402

[[92]]
[1] 0.2737343

[[93]]
[1] 2.032062

[[94]]
[1] 8.791474

[[95]]
[1] -0.2339733

[[96]]
[1] 3.272315

[[97]]
[1] -1.900928

[[98]]
[1] 5.791331

[[99]]
[1] -2.203777

[[100]]
[1] -8.262523

[[101]]
[1] 1.792908

[[102]]
[1] 3.033333

[[103]]
[1] 7.211942

[[104]]
[1] -2.207562

[[105]]
[1] 1.094935

[[106]]
[1] 0.097948

[[107]]
[1] -3.963499

[[108]]
[1] 0.9770066

[[109]]
[1] -3.871409

[[110]]
[1] 0.3334506

[[111]]
[1] -0.2041136

[[112]]
[1] -5.203949

[[113]]
[1] -2.204876

[[114]]
[1] -2.236787

[[115]]
[1] -1.963683

[[116]]
[1] -2.605458

[[117]]
[1] 0.8551617

[[118]]
[1] 0.9771402

[[119]]
[1] -1.017198

[[120]]
[1] 2.095433

[[121]]
[1] 5.034578

[[122]]
[1] -3.962425

[[123]]
[1] 6.793853

[[124]]
[1] -0.8099495

[[125]]
[1] -1.02671

[[126]]
[1] -5.203927

[[127]]
[1] -1.206463

[[128]]
[1] -0.1151285

[[129]]
[1] -2.203606

[[130]]
[1] -2.965392

[[131]]
[1] 3.156102

[[132]]
[1] -3.141521

[[133]]
[1] -6.715267

[[134]]
[1] -4.388371

[[135]]
[1] 1.726417

[[136]]
[1] 4.792916

[[137]]
[1] 4.852489

[[138]]
[1] 3.121486

[[139]]
[1] -1.722947

[[140]]
[1] 2.792769

[[141]]
[1] 1.791968

[[142]]
[1] -1.2066

[[143]]
[1] 1.880598

[[144]]
[1] 0.9856274

[[145]]
[1] 0.0981033

[[146]]
[1] -3.23364

[[147]]
[1] -3.200015

[[148]]
[1] 1.916951

[[149]]
[1] -5.201114

[[150]]
[1] 6.029686

[[151]]
[1] 0.9757361

[[152]]
[1] 1.97234

[[153]]
[1] 1.792118

[[154]]
[1] -3.204082

[[155]]
[1] 2.916004

[[156]]
[1] 5.79023

[[157]]
[1] -1.964623

[[158]]
[1] -0.2073908

[[159]]
[1] -4.204718

[[160]]
[1] -0.9673124

[[161]]
[1] 0.9434673

[[162]]
[1] -0.2058314

[[163]]
[1] 0.3058135

[[164]]
[1] -6.045792

[[165]]
[1] -4.206439

[[166]]
[1] 2.791495

[[167]]
[1] 0.7916539

[[168]]
[1] -2.633045

[[169]]
[1] 0.03506006

[[170]]
[1] -0.9064661

[[171]]
[1] 2.790222

[[172]]
[1] -2.206137

[[173]]
[1] 1.884253

[[174]]
[1] 5.032691

[[175]]
[1] -4.203289

[[176]]
[1] 1.335363

[[177]]
[1] 2.751237

[[178]]
[1] 2.455692

[[179]]
[1] -2.20534

[[180]]
[1] -0.208026

[[181]]
[1] -5.962083

[[182]]
[1] 1.274538

[[183]]
[1] -1.050666

[[184]]
[1] 6.791641

[[185]]
[1] -3.600807

[[186]]
[1] -2.051127

[[187]]
[1] -2.204721

[[188]]
[1] -2.631314

[[189]]
[1] 1.975733

[[190]]
[1] 2.033638

[[191]]
[1] -0.6619488

[[192]]
[1] -0.8116674

[[193]]
[1] 1.796221

[[194]]
[1] -1.665286

[[195]]
[1] 3.099348

[[196]]
[1] -1.484911

[[197]]
[1] 2.854062

[[198]]
[1] -1.208026

[[199]]
[1] -3.204089

[[200]]
[1] -0.6595989

[[201]]
[1] 4.969317

[[202]]
[1] 1.03459

[[203]]
[1] 6.975804

[[204]]
[1] -0.9673093

[[205]]
[1] -2.206133

[[206]]
[1] 4.273272

[[207]]
[1] -3.205975

[[208]]
[1] -4.200609

[[209]]
[1] 3.790702

[[210]]
[1] 0.7905302

[[211]]
[1] 0.7955966

[[212]]
[1] 1.275307

[[213]]
[1] -0.2035988

[[214]]
[1] 0.2746965

[[215]]
[1] -1.207239

[[216]]
[1] 3.977461

[[217]]
[1] 0.8839194

[[218]]
[1] -2.965722

[[219]]
[1] 2.034105

[[220]]
[1] -0.9673124

[[221]]
[1] 7.793367

[[222]]
[1] -0.725802

[[223]]
[1] 0.7529863

[[224]]
[1] -2.05192

[[225]]
[1] -0.206775

[[226]]
[1] 2.336305

[[227]]
[1] -1.724703

[[228]]
[1] 2.791499

[[229]]
[1] -1.205368

[[230]]
[1] 3.390739

[[231]]
[1] 6.790382

[[232]]
[1] 0.09575024

[[233]]
[1] -1.662273

[[234]]
[1] 2.792111

[[235]]
[1] 1.90911

[[236]]
[1] 0.09654077

[[237]]
[1] 3.272776

[[238]]
[1] -0.9635273

[[239]]
[1] -4.20346

[[240]]
[1] -1.206927

[[241]]
[1] 0.9744016

[[242]]
[1] -3.20534

[[243]]
[1] -2.961458

[[244]]
[1] 9.273096

[[245]]
[1] 4.573562

[[246]]
[1] 0.2176452

[[247]]
[1] 3.855621

[[248]]
[1] 0.7911686

[[249]]
[1] 1.215257

[[250]]
[1] -7.718989

[[251]]
[1] -2.143906

[[252]]
[1] -5.259886

[[253]]
[1] -0.2649188

[[254]]
[1] -5.016568

[[255]]
[1] 1.273576

[[256]]
[1] 7.033318

[[257]]
[1] 0.03191015

[[258]]
[1] -0.02506074

[[259]]
[1] -1.963334

[[260]]
[1] -1.141203

[[261]]
[1] 1.063498

[[262]]
[1] 2.427145

[[263]]
[1] 6.09397

[[264]]
[1] 0.7932219

[[265]]
[1] -1.785061

[[266]]
[1] 1.795261

[[267]]
[1] 0.03286231

[[268]]
[1] -5.264767

[[269]]
[1] 2.91291

[[270]]
[1] -0.2088197

[[271]]
[1] -3.964159

[[272]]
[1] -0.02380024

[[273]]
[1] 1.792603

[[274]]
[1] 1.333781

[[275]]
[1] -1.840428

[[276]]
[1] 0.09478495

[[277]]
[1] -0.1424604

[[278]]
[1] -4.111503

[[279]]
[1] 1.032065

[[280]]
[1] -1.965261

[[281]]
[1] -2.966052

[[282]]
[1] -1.964468

[[283]]
[1] -2.08099

[[284]]
[1] -1.964956

[[285]]
[1] -0.2663477

[[286]]
[1] -0.02254606

[[287]]
[1] 2.034126

[[288]]
[1] 1.975805

[[289]]
[1] -0.2654204

[[290]]
[1] 5.035815

[[291]]
[1] -3.962744

[[292]]
[1] 2.095585

[[293]]
[1] 3.792441

[[294]]
[1] 4.975879

[[295]]
[1] -1.205025

[[296]]
[1] 3.94102

[[297]]
[1] 1.972334

[[298]]
[1] -6.201898

[[299]]
[1] -3.900801

[[300]]
[1] 4.391663

[[301]]
[1] 5.035835

[[302]]
[1] -2.631

[[303]]
[1] -3.11164

[[304]]
[1] -2.203936

[[305]]
[1] -0.9042466

[[306]]
[1] 3.363942

[[307]]
[1] -0.9042498

[[308]]
[1] -3.205206

[[309]]
[1] -1.263992

[[310]]
[1] -0.9646262

[[311]]
[1] 5.78974

[[312]]
[1] 3.031428

[[313]]
[1] -3.810407

[[314]]
[1] 0.8587906

[[315]]
[1] 7.122747

[[316]]
[1] -0.2072355

[[317]]
[1] 7.909602

[[318]]
[1] 4.189119

[[319]]
[1] 0.7933749

[[320]]
[1] 1.9706

[[321]]
[1] -0.7246869

[[322]]
[1] 3.971379

[[323]]
[1] -0.9646293

[[324]]
[1] -0.4236037

[[325]]
[1] 3.095741

[[326]]
[1] 1.670913

[[327]]
[1] 0.7926029

[[328]]
[1] -1.207724

[[329]]
[1] 2.731603

[[330]]
[1] -0.2655572

[[331]]
[1] -3.205514

[[332]]
[1] -5.241324

[[333]]
[1] -1.022676

[[334]]
[1] -1.964931

[[335]]
[1] -2.054659

[[336]]
[1] 0.7941686

[[337]]
[1] 2.915213

[[338]]
[1] -0.01736001

[[339]]
[1] 2.916138

[[340]]
[1] 3.212267

[[341]]
[1] -4.204257

[[342]]
[1] -2.025603

[[343]]
[1] 2.976829

[[344]]
[1] -2.207562

[[345]]
[1] 5.730174

[[346]]
[1] -3.050822

[[347]]
[1] -2.025606

[[348]]
[1] -1.263992

[[349]]
[1] -1.146719

[[350]]
[1] -0.205193

[[351]]
[1] 2.338827

[[352]]
[1] 2.728912

[[353]]
[1] 6.030483

[[354]]
[1] -3.7217

[[355]]
[1] 1.094953

[[356]]
[1] 1.097154

[[357]]
[1] -2.027651

[[358]]
[1] -3.198122

[[359]]
[1] -0.9641462

[[360]]
[1] 0.9152166

[[361]]
[1] -0.9064661

[[362]]
[1] -0.2085145

[[363]]
[1] 6.032222

[[364]]
[1] -2.206769

[[365]]
[1] 0.4304697

[[366]]
[1] -2.962095

[[367]]
[1] 2.031116

[[368]]
[1] 3.792591

[[369]]
[1] 3.886924

[[370]]
[1] 5.450035

[[371]]
[1] 5.791331

[[372]]
[1] 1.793857

[[373]]
[1] -4.047366

[[374]]
[1] 2.85359

[[375]]
[1] -0.7802234

[[376]]
[1] 0.7911771

[[377]]
[1] -0.08242399

[[378]]
[1] -0.8462861

[[379]]
[1] -0.2078793

[[380]]
[1] 8.21099

[[381]]
[1] -3.025469

[[382]]
[1] -0.204095

[[383]]
[1] -5.203594

[[384]]
[1] -2.204086

[[385]]
[1] 2.274033

[[386]]
[1] 0.09793171

[[387]]
[1] -1.022213

[[388]]
[1] -2.56969

[[389]]
[1] 8.273099

[[390]]
[1] -2.960841

[[391]]
[1] 0.5806379

[[392]]
[1] 1.271525

[[393]]
[1] 2.971693

[[394]]
[1] 3.091462

[[395]]
[1] 1.976038

[[396]]
[1] 1.452846

[[397]]
[1] -1.264475

[[398]]
[1] -6.201434

[[399]]
[1] 6.913766

[[400]]
[1] 2.096341

[[401]]
[1] -2.201732

[[402]]
[1] -2.481897

[[403]]
[1] -1.022543

[[404]]
[1] -5.199992

[[405]]
[1] 0.1877105

[[406]]
[1] 3.733484

[[407]]
[1] -0.7816578

[[408]]
[1] 2.220245

[[409]]
[1] 2.094795

[[410]]
[1] 2.970442

[[411]]
[1] 3.884859

[[412]]
[1] -6.138385

[[413]]
[1] 0.7614641

[[414]]
[1] 1.034269

[[415]]
[1] -1.724678

[[416]]
[1] -2.966186

[[417]]
[1] -8.138982

[[418]]
[1] -0.08496038

[[419]]
[1] 4.796212

[[420]]
[1] 3.038039

[[421]]
[1] -4.108842

[[422]]
[1] 0.7529863

[[423]]
[1] -4.202523

[[424]]
[1] 5.090361

[[425]]
[1] -6.202228

[[426]]
[1] 2.362688

[[427]]
[1] 3.855632

[[428]]
[1] 4.032534

[[429]]
[1] 0.03347809

[[430]]
[1] 1.731598

[[431]]
[1] 1.272474

[[432]]
[1] -1.961968

[[433]]
[1] 0.03206545

[[434]]
[1] 6.273574

[[435]]
[1] 2.032062

[[436]]
[1] 2.213073

[[437]]
[1] -5.202828

[[438]]
[1] -3.902367

[[439]]
[1] -1.146255

[[440]]
[1] 1.851532

[[441]]
[1] 4.791334

[[442]]
[1] -3.264602

[[443]]
[1] 3.883908

[[444]]
[1] -3.782546

[[445]]
[1] -0.1456234

[[446]]
[1] 1.971219

[[447]]
[1] -3.046112

[[448]]
[1] 1.152365

[[449]]
[1] 0.8565897

[[450]]
[1] -1.780706

[[451]]
[1] 3.638495

[[452]]
[1] 5.031432

[[453]]
[1] 2.857069

[[454]]
[1] -2.113227

[[455]]
[1] -1.965722

[[456]]
[1] 2.791016

[[457]]
[1] -2.201577

[[458]]
[1] 2.336461

[[459]]
[1] -1.023312

[[460]]
[1] 6.031428

[[461]]
[1] 2.790063

[[462]]
[1] -2.901735

[[463]]
[1] 2.335667

[[464]]
[1] -4.721395

[[465]]
[1] -0.02270136

[[466]]
[1] 5.969314

[[467]]
[1] -9.199825

[[468]]
[1] -3.266513

[[469]]
[1] 2.852478

[[470]]
[1] -4.053502

[[471]]
[1] -6.139467

[[472]]
[1] -3.202209

[[473]]
[1] 2.030316

[[474]]
[1] 1.216144

[[475]]
[1] 1.672822

[[476]]
[1] -1.080049

[[477]]
[1] -3.267745

[[478]]
[1] -2.391544

[[479]]
[1] 2.032523

[[480]]
[1] 0.2164497

[[481]]
[1] 0.8263814

[[482]]
[1] -0.08288763

[[483]]
[1] -1.781124

[[484]]
[1] 2.033796

[[485]]
[1] 4.791797

[[486]]
[1] -1.902662

[[487]]
[1] 4.390406

[[488]]
[1] -0.9009477

[[489]]
[1] -1.206775

[[490]]
[1] -1.205188

[[491]]
[1] -2.204876

[[492]]
[1] -2.206927

[[493]]
[1] 2.668552

[[494]]
[1] 0.09274024

[[495]]
[1] 3.91978

[[496]]
[1] 6.034267

[[497]]
[1] 1.915852

[[498]]
[1] 2.915693

[[499]]
[1] -1.96621

[[500]]
[1] 9.031879

[[501]]
[1] -5.896242

[[502]]
[1] -4.141982

[[503]]
[1] -0.6646319

[[504]]
[1] 1.094163

[[505]]
[1] 4.449823

[[506]]
[1] 3.730499

[[507]]
[1] 5.791486

[[508]]
[1] -1.146084

[[509]]
[1] -2.203295

[[510]]
[1] 0.8534276

[[511]]
[1] -0.2062919

[[512]]
[1] 1.511936

[[513]]
[1] 5.824359

[[514]]
[1] -1.142919

[[515]]
[1] -2.485546

[[516]]
[1] -1.14182

[[517]]
[1] 0.2175517

[[518]]
[1] -1.145135

[[519]]
[1] -0.2070887

[[520]]
[1] 1.185491

[[521]]
[1] -0.7822898

[[522]]
[1] 1.038367

[[523]]
[1] 0.8545265

[[524]]
[1] 1.182316

[[525]]
[1] 9.030781

[[526]]
[1] 2.980891

[[527]]
[1] -0.7850696

[[528]]
[1] 0.7918155

[[529]]
[1] -0.6627393

[[530]]
[1] -2.544306

[[531]]
[1] 0.8859704

[[532]]
[1] -1.965258

[[533]]
[1] -0.2064666

[[534]]
[1] -1.482078

[[535]]
[1] -2.632104

[[536]]
[1] -3.811197

[[537]]
[1] -1.203005

[[538]]
[1] -0.02749871

[[539]]
[1] 2.731773

[[540]]
[1] 0.8001443

[[541]]
[1] -1.145141

[[542]]
[1] -1.208026

[[543]]
[1] 5.798115

[[544]]
[1] 0.9166293

[[545]]
[1] -0.2664976

[[546]]
[1] 0.7935465

[[547]]
[1] -1.05714

[[548]]
[1] 2.27277

[[549]]
[1] -1.296036

[[550]]
[1] -7.898862

[[551]]
[1] 1.033014

[[552]]
[1] -0.08447186

[[553]]
[1] 6.217395

[[554]]
[1] 3.791012

[[555]]
[1] -2.902831

[[556]]
[1] -1.142919

[[557]]
[1] 3.033952

[[558]]
[1] -4.201729

[[559]]
[1] -2.811514

[[560]]
[1] 1.915061

[[561]]
[1] -2.204416

[[562]]
[1] 7.916927

[[563]]
[1] -1.029413

[[564]]
[1] -0.205193

[[565]]
[1] -2.205184

[[566]]
[1] 0.7542405

[[567]]
[1] 5.034095

[[568]]
[1] -2.202835

[[569]]
[1] 1.970117

[[570]]
[1] -4.785985

[[571]]
[1] -2.204072

[[572]]
[1] -2.113688

[[573]]
[1] -1.838732

[[574]]
[1] 4.788628

[[575]]
[1] -3.143874

[[576]]
[1] 0.3915204

[[577]]
[1] -0.9042715

[[578]]
[1] 3.156737

[[579]]
[1] 1.853421

[[580]]
[1] 2.793865

[[581]]
[1] 0.6724921

[[582]]
[1] -1.965722

[[583]]
[1] -1.205498

[[584]]
[1] -1.901894

[[585]]
[1] -3.203292

[[586]]
[1] 0.9142676

[[587]]
[1] 2.731134

[[588]]
[1] -2.724675

[[589]]
[1] -0.0854186

[[590]]
[1] 2.792425

[[591]]
[1] 4.096046

[[592]]
[1] -6.958336

[[593]]
[1] 1.79086

[[594]]
[1] -1.205498

[[595]]
[1] -1.965557

[[596]]
[1] 7.031581

[[597]]
[1] 0.3400842

[[598]]
[1] -0.966674

[[599]]
[1] 0.274361

[[600]]
[1] 6.033321

[[601]]
[1] 5.976043

[[602]]
[1] 1.790225

[[603]]
[1] 1.272954

[[604]]
[1] -1.965404

[[605]]
[1] 7.976208

[[606]]
[1] 3.575453

[[607]]
[1] 1.793702

[[608]]
[1] -2.206769

[[609]]
[1] 3.79369

[[610]]
[1] -0.9344395

[[611]]
[1] 2.095741

[[612]]
[1] 0.7918124

[[613]]
[1] -0.6641651

[[614]]
[1] 3.914589

[[615]]
[1] -3.202828

[[616]]
[1] -4.142617

[[617]]
[1] -0.0228544

[[618]]
[1] 6.211632

[[619]]
[1] -3.205975

[[620]]
[1] -3.205511

[[621]]
[1] 3.272792

[[622]]
[1] -1.904418

[[623]]
[1] 1.273747

[[624]]
[1] -0.2653987

[[625]]
[1] -2.203797

[[626]]
[1] 3.211307

[[627]]
[1] 1.851687

[[628]]
[1] -2.147052

[[629]]
[1] 1.82118

[[630]]
[1] 5.9762

[[631]]
[1] 5.032536

[[632]]
[1] 6.032067

[[633]]
[1] 7.035207

[[634]]
[1] -2.902199

[[635]]
[1] -3.203463

[[636]]
[1] 7.214245

[[637]]
[1] 4.215514

[[638]]
[1] 4.216615

[[639]]
[1] -1.967931

[[640]]
[1] 8.215979

[[641]]
[1] 3.974467

[[642]]
[1] 2.095259

[[643]]
[1] -4.202389

[[644]]
[1] 2.972333

[[645]]
[1] 0.09763965

[[646]]
[1] -4.296046

[[647]]
[1] 2.332676

[[648]]
[1] 3.151433

[[649]]
[1] 2.035842

[[650]]
[1] -1.964471

[[651]]
[1] 0.03521537

[[652]]
[1] 0.7948138

[[653]]
[1] 2.03507

[[654]]
[1] 2.095433

[[655]]
[1] 4.095738

[[656]]
[1] -0.1437308

[[657]]
[1] -8.20031

[[658]]
[1] -2.11197

[[659]]
[1] -0.2097719

[[660]]
[1] -0.2026715

[[661]]
[1] 2.098726

[[662]]
[1] -1.205978

[[663]]
[1] 5.03253

[[664]]
[1] 0.8531224

[[665]]
[1] -2.020984

[[666]]
[1] 1.971235

[[667]]
[1] 5.2196

[[668]]
[1] 2.79275

[[669]]
[1] -1.723735

[[670]]
[1] -2.204549

[[671]]
[1] -2.051127

[[672]]
[1] 5.333604

[[673]]
[1] 4.792918

[[674]]
[1] 4.033171

[[675]]
[1] 3.271205

[[676]]
[1] 0.9776418

[[677]]
[1] 3.792902

[[678]]
[1] 2.155314

[[679]]
[1] 2.887395

[[680]]
[1] 3.791806

[[681]]
[1] -2.205975

[[682]]
[1] 1.792603

[[683]]
[1] 4.796212

[[684]]
[1] -0.9627205

[[685]]
[1] -1.051612

[[686]]
[1] -0.78568

[[687]]
[1] 3.915055

[[688]]
[1] 4.334406

[[689]]
[1] -0.9026655

[[690]]
[1] 3.790702

[[691]]
[1] -3.203793

[[692]]
[1] 0.03346318

[[693]]
[1] -2.963674

[[694]]
[1] 2.276081

[[695]]
[1] 1.336155

[[696]]
[1] 2.975063

[[697]]
[1] -4.722185

[[698]]
[1] 0.2724738

[[699]]
[1] 1.854856

[[700]]
[1] 3.450948

[[701]]
[1] -2.78313

[[702]]
[1] -0.207244

[[703]]
[1] -4.262242

[[704]]
[1] -0.2669861

[[705]]
[1] 2.336461

[[706]]
[1] -1.142782

[[707]]
[1] -0.9647815

[[708]]
[1] -0.2073908

[[709]]
[1] 0.03346951

[[710]]
[1] -5.233945

[[711]]
[1] 1.729067

[[712]]
[1] -2.201599

[[713]]
[1] -0.1456352

[[714]]
[1] 1.273744

[[715]]
[1] -2.025448

[[716]]
[1] -2.023642

[[717]]
[1] 0.1546823

[[718]]
[1] 2.392174

[[719]]
[1] 5.788004

[[720]]
[1] 1.216141

[[721]]
[1] 1.096674

[[722]]
[1] -1.269209

[[723]]
[1] 4.095097

[[724]]
[1] -0.2080292

[[725]]
[1] -2.206133

[[726]]
[1] -1.027346

[[727]]
[1] 3.729078

[[728]]
[1] 5.091775

[[729]]
[1] -1.903161

[[730]]
[1] 1.947119

[[731]]
[1] -1.266348

[[732]]
[1] 2.791016

[[733]]
[1] -2.964468

[[734]]
[1] -2.053505

[[735]]
[1] -1.664032

[[736]]
[1] 3.790699

[[737]]
[1] -2.898439

[[738]]
[1] 0.03316749

[[739]]
[1] 4.668548

[[740]]
[1] 1.854545

[[741]]
[1] 1.063656

[[742]]
[1] -1.541548

[[743]]
[1] 2.972173

[[744]]
[1] 5.216606

[[745]]
[1] 0.03285915

[[746]]
[1] -0.2680818

[[747]]
[1] -4.964134

[[748]]
[1] 0.7529831

[[749]]
[1] -0.9660583

[[750]]
[1] -2.205016

[[751]]
[1] -0.9036277

[[752]]
[1] 0.8886558

[[753]]
[1] -0.2088197

[[754]]
[1] 0.03395486

[[755]]
[1] -2.964626

[[756]]
[1] 3.792267

[[757]]
[1] 1.097792

[[758]]
[1] -1.785195

[[759]]
[1] -2.019221

[[760]]
[1] 0.7921207

[[761]]
[1] 5.791179

[[762]]
[1] 5.030641

[[763]]
[1] 4.790699

[[764]]
[1] 3.790852

[[765]]
[1] -2.207562

[[766]]
[1] -0.146414

[[767]]
[1] -1.083193

[[768]]
[1] 6.913766

[[769]]
[1] 4.792103

[[770]]
[1] -2.083038

[[771]]
[1] 2.974839

[[772]]
[1] 3.852802

[[773]]
[1] -0.2061366

[[774]]
[1] 3.793226

[[775]]
[1] 0.7910218

[[776]]
[1] 1.032526

[[777]]
[1] -1.20567

[[778]]
[1] 2.333781

[[779]]
[1] -1.205978

[[780]]
[1] -1.14483

[[781]]
[1] 3.79354

[[782]]
[1] 0.6722001

[[783]]
[1] -0.8448572

[[784]]
[1] 4.791175

[[785]]
[1] 2.852009

[[786]]
[1] -1.965722

[[787]]
[1] -0.1446744

[[788]]
[1] -5.016551

[[789]]
[1] -5.961448

[[790]]
[1] -2.206295

[[791]]
[1] 1.854367

[[792]]
[1] -6.2028

[[793]]
[1] -0.2072355

[[794]]
[1] -0.02254606

[[795]]
[1] 1.032681

[[796]]
[1] -3.204257

[[797]]
[1] 5.149692

[[798]]
[1] -1.089291

[[799]]
[1] -0.9064661

[[800]]
[1] 4.2174

[[801]]
[1] -1.264916

[[802]]
[1] 0.1559333

[[803]]
[1] -0.7867625

[[804]]
[1] 5.794012

[[805]]
[1] -0.965423

[[806]]
[1] 4.791179

[[807]]
[1] -2.049873

[[808]]
[1] 3.734755

[[809]]
[1] -0.2056729

[[810]]
[1] 6.210533

[[811]]
[1] 1.33299

[[812]]
[1] -4.90078

[[813]]
[1] -3.960356

[[814]]
[1] 1.271525

[[815]]
[1] -1.958956

[[816]]
[1] 0.7959027

[[817]]
[1] -1.202681

[[818]]
[1] 4.031745

[[819]]
[1] -6.781416

[[820]]
[1] 5.096037

[[821]]
[1] -1.965725

[[822]]
[1] 5.731913

[[823]]
[1] -2.903161

[[824]]
[1] -4.140883

[[825]]
[1] 6.03301

[[826]]
[1] 4.730182

[[827]]
[1] -1.964141

[[828]]
[1] -0.05610969

[[829]]
[1] 1.095106

[[830]]
[1] -10.19482

[[831]]
[1] -0.9660551

[[832]]
[1] -2.724675

[[833]]
[1] -0.7237247

[[834]]
[1] -1.024105

[[835]]
[1] -0.2048878

[[836]]
[1] 2.696409

[[837]]
[1] -0.2072355

[[838]]
[1] -2.903951

[[839]]
[1] 1.792911

[[840]]
[1] -3.116859

[[841]]
[1] 6.794952

[[842]]
[1] 0.2731154

[[843]]
[1] 2.791651

[[844]]
[1] 2.942051

[[845]]
[1] -2.112434

[[846]]
[1] -1.144833

[[847]]
[1] -0.1460839

[[848]]
[1] 1.217085

[[849]]
[1] -2.202853

[[850]]
[1] 5.031587

[[851]]
[1] 2.032542

[[852]]
[1] -1.724681

[[853]]
[1] 2.187549

[[854]]
[1] -1.267621

[[855]]
[1] 1.855638

[[856]]
[1] -4.140114

[[857]]
[1] -0.7853531

[[858]]
[1] 4.153721

[[859]]
[1] 3.032698

[[860]]
[1] 2.513512

[[861]]
[1] -3.140251

[[862]]
[1] 0.7918124

[[863]]
[1] -2.111643

[[864]]
[1] -1.206769

[[865]]
[1] -0.9627399

[[866]]
[1] -7.200152

[[867]]
[1] -2.725139

[[868]]
[1] -2.205514

[[869]]
[1] -4.173734

[[870]]
[1] 7.271523

[[871]]
[1] -1.965087

[[872]]
[1] -0.2061366

[[873]]
[1] -2.265221

[[874]]
[1] -8.022469

[[875]]
[1] 3.031904

[[876]]
[1] -2.779778

[[877]]
[1] -4.022917

[[878]]
[1] -2.812785

[[879]]
[1] 5.791334

[[880]]
[1] -1.206756

[[881]]
[1] 1.792428

[[882]]
[1] 2.096208

[[883]]
[1] 6.791017

[[884]]
[1] -2.237275

[[885]]
[1] -0.2066002

[[886]]
[1] -0.968103

[[887]]

In [ ]:
df <- as.data.frame(array(unlist(n_c_list),dim=c(3864, 1)))
df

     V1
1     2.79242500
2     1.73270011
3     0.21803074
4     2.79259432
5     0.03143338
6    -7.96003241
7     4.79164759
8    -2.78112056
9    -2.02095550
10   -0.11417946
11    0.66981760
12    3.36930549
13    1.33962051
14   11.88139432
15   -2.26601135
16   -2.23694532
17    0.51383210
18    0.97106061
19   -1.90173508
20   -2.20835605
21   -1.14449967
22   -3.20723230
23   -1.20692712
24   -0.14592860
25   -0.66541929
26   -1.96447629
27   -2.01735142
28    1.79244761
29   -1.72435997
30    6.72986307
⋮    ⋮
3835  0.97076175
3836  1.97557765
3837  1.21897974
3838 -2.01952973
3839  2.03172591
3840 -0.02728021
3841  3.21548802
3842 -0.08321768
3843  0.79339661
3844  9.33469670
3845  2.97557449
3846 -5.77803244
3847  2.21583073
3848 -1.01544798
3849 -0.02285124
3850 22.57303870
3851  1.93640345
3852 11.12370070
3853  6.17112235
3854  1.81507510
3855 -3.10803492
3856 17.21436839
3857 15.21547585
3858 -4.77865455
3859  3.97635960
3860 -0.85898302
3861  2.21455393
3862  1.97636819
3863 13.91281478
3864  5.22212245

In [ ]:
write.csv(df,"/content/netchargedata.csv", col.names = 'net_charge')

Warning message in write.csv(df, "/content/netchargedata.csv", col.names = "net_charge"):
“attempt to set 'col.names' ignored”

In [ ]:
nrow(pep_data)

[1] 3864

In [ ]:
seq = "EDDHHHHHHHHHGVGGGGGGGGGG"
charge(seq,pH= 7, pKscale= "EMBOSS")

[1] -0.858983

# Extract Dipeptide Composition

In [ ]:
#install.packages("protr")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [ ]:
library("protr")

In [ ]:
pep_data <- read.csv("/content/peptide.csv")

pep_data

     Category Sequence
1    toxin    ACSGRGSRCPPQCCMGLTCGREYPPRC
2    toxin    CGPCFTKDPETEKKCATCCGGIGRCFGPQCLCNRGY
3    toxin    MSDINATRLPHLVRYPPYVGDGTDLTLNRGEK
4    toxin    QKELVVTATTTCCGYNPMTSCPRCMCDSSCNKKKP
5    toxin    CCPFPMCYQVPHCPCC
6    toxin    CTENGDVCDPENHNCCSGSCLDDEDPPVCGF
7    toxin    CKGRGGACTKAMFICCSGSCNRGRC
8    toxin    SCDSEFSSEFCEQPEERICSCSTHVCCHLSSSKRDQCMTWNRCLSAQTGN
9    toxin    VATSEQFNKTFIELVIVVD
10   toxin    DGVCSNRRQCNKEVCGSSYDVAIVGA
11   toxin    SGSTCTCFTSTNCQGSCECLSPPGCYCSNNGIRQRGCSCTCPGT
12   toxin    ASNHENSKGSTRNGRHTIQECCMDPVCRLIIEKFGKDFAAALDFRRLPYR
13   toxin    SDGRDDEAKDERPDMYKSKRDGRCCHPACAKHFNCGR
14   toxin    LKCKNKVVPFLKCKNKVVPFLCYKMTLKKVTPKIKRG
15   toxin    KQCTSNMCSADCSPGCCIIDKLEWCTCDC
16   toxin    GKCGDINAPCKAECDCCGYTTCDCYWGN
17   toxin    TCSPAGEVCTSKSPCCTGFLCSHIGGMCHH
18   toxin    ACVGENKQCADWAGPHCCDGYYCTCRYFPKCICRNNN
19   toxin    DAADVKPVARTNEGPGRDPAPCCQHPIETCC
20   toxin    CYGFGEACLVLYTDCCGYCVLAVCL
21   toxin    TLLNILRDGDNCCIDKQGCCPW
22   toxin    DCQALWDYCPVPLLSSGDCCYGLICGPFVCIGW
23   toxin    CLSGGEVCDFLFPKCCNYCILLFCS
24   toxin    GCCSRPPCIANNPDIC
25   toxin    DGCPPHPVPGMHPCMCTNTC
26   toxin    TCVMFGSMCDKEEHSICCYECDYKKGICV
27   toxin    GDEEYSKMAAEREREAGRLDLSKFP
28   toxin    CTPAGKACDATATCCVLFCNLVTNKCQVPRFP
29   toxin    GVDKEGCRYLLGACTIDDDCCLHLGCNKKYGHCGWDGTF
30   toxin    AAAISCVGSKECLPKCKAQGCKSGKCMNKKCKCYC
⋮    ⋮        ⋮
3835 non-t    MAPCSCKSCGTSCAGSCTSCSCGSCSH
3836 non-t    FIGTALGIASAIPAIVKLFK
3837 non-t    HSDGTFTSELSRLRDSARLQRLLQGLV
3838 non-t    GKAFDDGAFTGIREINLSINKETAIGD
3839 non-t    YVGQRLCGSQLVDTLYSVCKHRGFYRPSEGIVDQCCTNICSRNQLLTYCN
3840 non-t    MMNLLSGWFYILMFYIGVNFPYWMGWSTTAFGFYTP
3841 non-t    NVSLITAFDNLDLSRKGAYYLYYLLSERLKRGGVPVHVNRA
3842 non-t    MCIFFFFKKLFFVEINVCLSFFFLFYFIFVLFFAAEVRNNDF
3843 non-t    GCPRILMRCKQDSDCLAGCVCGPNGFCGSP
3844 non-t    MRQKVTLACVQCASRNYTAAKQIRRLGERLMANKFCSTCNKHTIHRETK
3845 non-t    GKTKGVTSGLIAFPRL
3846 non-t    MEPAIVLIISVGAALVAVTGYGIYTAFGPPSRELSDPFEDHED
3847 non-t    MTTFNNLPSIFVPLVGLVFPAIAMASLFLHIQKNKIF
3848 non-t    MSDKPDISEVTSFDKTKLKKTETQEKNPLPSKETIEQEKAAATS
3849 non-t    MNLEIVFQLTALLFVVAAGPLVIVLLASRGGNL
3850 non-t    MKCGRKRRRRRRHACKRKKRACKQRSSTIVRAHLVHRRRAARRCP
3851 non-t    MVILLHKFQLDELIYIVLAQGYHQIPEYVRFQFPLYAHKDIHLYMKKLVL
3852 non-t    MKVRASVKKMCDNCRVIKRKGKVMVICSNAKHKQRQG
3853 non-t    MLKYIYMHLSHKYNHILFTYNMRIYLIKRNHMLFTHMFTTYAYIM
3854 non-t    SHQDCYEALHKCMASHSKPFSCSMKFHMCLQQQ
3855 non-t    MKNSKDILNNAIEEVSEKELMEVAGGKRGSGWIATITDDCPNSVFVCC
3856 non-t    MKRTYQPSVTRRKRTHGFRVRMKTAGGRKVINARRAKGRKRLAI
3857 non-t    MKIRNSLRSLRNRHRDNRLVRRKGRVYIINKTNRRFKARQG
3858 non-t    METATVLIVFIASLLLGVTGYSVYTAFGPNSKDLRDPFEDHED
3859 non-t    GLWSKIKEAGKAAVKAAGKAALGAVANSV
3860 non-t    EDDHHHHHHHHHGVGGGGGGGGGG
3861 non-t    MTTNTQYIYPIFTVRWLAVHALAVPTVFFLGSISAMQFIQR
3862 non-t    GILDVAKTLVGKLRNVLGI
3863 non-t    MKVLSSLASAKTRYPDCQVVRRRGRVYVICKSNPRFKAVQGRKKRR
3864 non-t    MKSIDLTILSLKRKGIRTEKVLKNQNPDRLSHMTDKNAQPKSKEKEE

In [ ]:
dc_list = list()

for (row in 1:nrow(pep_data)){
  seq <- pep_data[row, "Sequence"]
  #print(seq)
  dc_list <- c(dc_list, seq)
}

In [ ]:
length(dc_list)

[1] 3864

In [ ]:
x2 <- t(sapply(dc_list, extractDC))
colnames(x2)[colnames(x2) == "NA"] <- "NA_dipeptide"
x2

      AA         RA         NA_dipeptide DA         CA         EA
 [1,] 0.00000000 0          0.00000000   0.00000000 0.00000000 0.00000000
 [2,] 0.00000000 0          0.00000000   0.00000000 0.02857143 0.00000000
 [3,] 0.00000000 0          0.03225806   0.00000000 0.00000000 0.00000000
 [4,] 0.00000000 0          0.00000000   0.00000000 0.00000000 0.00000000
 [5,] 0.00000000 0          0.00000000   0.00000000 0.00000000 0.00000000
 [6,] 0.00000000 0          0.00000000   0.00000000 0.00000000 0.00000000
 [7,] 0.00000000 0          0.00000000   0.00000000 0.00000000 0.00000000
 [8,] 0.00000000 0          0.00000000   0.00000000 0.00000000 0.00000000
 [9,] 0.00000000 0          0.00000000   0.00000000 0.00000000 0.00000000
[10,] 0.00000000 0          0.00000000   0.00000000 0.00000000 0.00000000
[11,] 0.00000000 0          0.00000000   0.00000000 0.00000000 0.00000000
[12,] 0.04081633 0          0.00000000   0.00000000 0.00000000 0.00000000
[13,] 0.00000000 0          0.00000000   0.00000000 0.02777778 0.02777778
[14,] 0.00000000 0          0.00000000   0.00000000 0.00000000 0.00000000
[15,] 0.00000000 0          0.00000000   0.00000000 0.00000000 0.00000000
[16,] 0.00000000 0          0.03703704   0.00000000 0.00000000 0.00000000
[17,] 0.00000000 0          0.00000000   0.00000000 0.00000000 0.00000000
[18,] 0.00000000 0          0.00000000   0.00000000 0.02777778 0.00000000
[19,] 0.03333333 0          0.00000000   0.03333333 0.00000000 0.00000000
[20,] 0.00000000 0          0.00000000   0.00000000 0.00000000 0.04166667
[21,] 0.00000000 0          0.00000000   0.00000000 0.00000000 0.00000000
[22,] 0.00000000 0          0.00000000   0.00000000 0.00000000 0.00000000
[23,] 0.00000000 0          0.00000000   0.00000000 0.00000000 0.00000000
[24,] 0.00000000 0          0.00000000   0.00000000 0.00000000 0.00000000
[25,] 0.00000000 0          0.00000000   0.00000000 0.00000000 0.00000000
[26,] 0.00000000 0          0.00000000   0.00000000 0.00000000 0.00000000
[27,] 0.04166667 0          0.00000000   0.00000000 0.00000000 0.04166667
[28,] 0.00000000 0          0.00000000   0.03225806 0.00000000 0.00000000
[29,] 0.00000000 0          0.00000000   0.00000000 0.00000000 0.00000000
[30,] 0.05882353 0          0.00000000   0.00000000 0.00000000 0.00000000
[31,] ⋮          ⋮          ⋮            ⋮          ⋮          ⋮
[32,] 0.00000000 0.00000000 0.00000000   0          0.03846154 0.00000000
[33,] 0.00000000 0.00000000 0.00000000   0          0.00000000 0.00000000
[34,] 0.00000000 0.00000000 0.00000000   0          0.00000000 0.00000000
[35,] 0.00000000 0.00000000 0.00000000   0          0.00000000 0.00000000
[36,] 0.00000000 0.00000000 0.00000000   0          0.00000000 0.00000000
[37,] 0.00000000 0.00000000 0.00000000   0          0.00000000 0.00000000
[38,] 0.00000000 0.02500000 0.00000000   0          0.00000000 0.00000000
[39,] 0.02439024 0.00000000 0.00000000   0          0.00000000 0.00000000
[40,] 0.00000000 0.00000000 0.00000000   0          0.00000000 0.00000000
[41,] 0.02083333 0.00000000 0.00000000   0          0.02083333 0.00000000
[42,] 0.00000000 0.00000000 0.00000000   0          0.00000000 0.00000000
[43,] 0.02380952 0.00000000 0.00000000   0          0.00000000 0.00000000
[44,] 0.00000000 0.00000000 0.00000000   0          0.00000000 0.00000000
[45,] 0.04651163 0.00000000 0.00000000   0          0.00000000 0.00000000
[46,] 0.03125000 0.00000000 0.00000000   0          0.00000000 0.00000000
[47,] 0.02272727 0.06818182 0.00000000   0          0.00000000 0.00000000
[48,] 0.00000000 0.00000000 0.00000000   0          0.00000000 0.00000000
[49,] 0.00000000 0.02777778 0.02777778   0          0.00000000 0.00000000
[50,] 0.00000000 0.00000000 0.00000000   0          0.00000000 0.00000000
[51,] 0.00000000 0.00000000 0.00000000   0          0.00000000 0.03125000
[52,] 0.00000000 0.00000000 0.02127660   0          0.00000000 0.00000000
[53,] 0.00000000 0.02325581 0.02325581   0          0.00000000 0.00000000
[54,] 0.00000000 0.00000000 0.00000000   0          0.00000000 0.00000000
[55,] 0.00000000 0.00000000 0.00000000   0          0.00000000 0.00000000
[56,] 0.10714286 0.00000000 0.00000000   0          0.00000000 0.03571429
[57,] 0.00000000 0.00000000 0.00000000   0          0.00000000 0.00000000
[58,] 0.00000000 0.00000000 0.00000000   0          0.00000000 0.00000000
[59,] 0.00000000 0.00000000 0.00000000   0          0.00000000 0.00000000
[60,] 0.00000000 0.00000000 0.00000000   0          0.00000000 0.00000000
[61,] 0.00000000 0.00000000 0.02173913   0          0.00000000 0.00000000
      QA      GA         HA         IA         ⋯ LV         KV
 [1,] 0.00000 0.00000000 0          0.00000000 ⋯ 0.00000000 0.00000000
 [2,] 0.00000 0.00000000 0          0.00000000 ⋯ 0.00000000 0.00000000
 [3,] 0.00000 0.00000000 0          0.00000000 ⋯ 0.03225806 0.00000000
 [4,] 0.00000 0.00000000 0          0.00000000 ⋯ 0.02941176 0.00000000
 [5,] 0.00000 0.00000000 0          0.00000000 ⋯ 0.00000000 0.00000000
 [6,] 0.00000 0.00000000 0          0.00000000 ⋯ 0.00000000 0.00000000
 [7,] 0.00000 0.04166667 0          0.00000000 ⋯ 0.00000000 0.00000000
 [8,] 0.00000 0.00000000 0          0.00000000 ⋯ 0.00000000 0.00000000
 [9,] 0.00000 0.00000000 0          0.00000000 ⋯ 0.05555556 0.00000000
[10,] 0.00000 0.04000000 0          0.00000000 ⋯ 0.00000000 0.00000000
[11,] 0.00000 0.00000000 0          0.00000000 ⋯ 0.00000000 0.00000000
[12,] 0.00000 0.00000000 0          0.00000000 ⋯ 0.00000000 0.00000000
[13,] 0.00000 0.00000000 0          0.00000000 ⋯ 0.00000000 0.00000000
[14,] 0.00000 0.00000000 0          0.00000000 ⋯ 0.00000000 0.08333333
[15,] 0.00000 0.00000000 0          0.00000000 ⋯ 0.00000000 0.00000000
[16,] 0.00000 0.00000000 0          0.00000000 ⋯ 0.00000000 0.00000000
[17,] 0.00000 0.00000000 0          0.00000000 ⋯ 0.00000000 0.00000000
[18,] 0.00000 0.00000000 0          0.00000000 ⋯ 0.00000000 0.00000000
[19,] 0.00000 0.00000000 0          0.00000000 ⋯ 0.00000000 0.00000000
[20,] 0.00000 0.00000000 0          0.00000000 ⋯ 0.04166667 0.00000000
[21,] 0.00000 0.00000000 0          0.00000000 ⋯ 0.00000000 0.00000000
[22,] 0.03125 0.00000000 0          0.00000000 ⋯ 0.00000000 0.00000000
[23,] 0.00000 0.00000000 0          0.00000000 ⋯ 0.00000000 0.00000000
[24,] 0.00000 0.00000000 0          0.06666667 ⋯ 0.00000000 0.00000000
[25,] 0.00000 0.00000000 0          0.00000000 ⋯ 0.00000000 0.00000000
[26,] 0.00000 0.00000000 0          0.00000000 ⋯ 0.00000000 0.00000000
[27,] 0.00000 0.00000000 0          0.00000000 ⋯ 0.00000000 0.00000000
[28,] 0.00000 0.00000000 0          0.00000000 ⋯ 0.03225806 0.00000000
[29,] 0.00000 0.02631579 0          0.00000000 ⋯ 0.00000000 0.00000000
[30,] 0.00000 0.00000000 0          0.00000000 ⋯ 0.00000000 0.00000000
[31,] ⋮       ⋮          ⋮          ⋮          ⋱ ⋮          ⋮
[32,] 0       0.00000000 0.00000000 0.00000000 ⋯ 0.00000000 0.00000000
[33,] 0       0.00000000 0.00000000 0.05263158 ⋯ 0.00000000 0.00000000
[34,] 0       0.00000000 0.00000000 0.00000000 ⋯ 0.03846154 0.00000000
[35,] 0       0.03846154 0.00000000 0.00000000 ⋯ 0.00000000 0.00000000
[36,] 0       0.00000000 0.00000000 0.00000000 ⋯ 0.02040816 0.00000000
[37,] 0       0.00000000 0.00000000 0.00000000 ⋯ 0.00000000 0.00000000
[38,] 0       0.02500000 0.00000000 0.00000000 ⋯ 0.00000000 0.00000000
[39,] 0       0.00000000 0.00000000 0.00000000 ⋯ 0.00000000 0.00000000
[40,] 0       0.00000000 0.00000000 0.00000000 ⋯ 0.00000000 0.00000000
[41,] 0       0.00000000 0.00000000 0.00000000 ⋯ 0.00000000 0.02083333
[42,] 0       0.00000000 0.00000000 0.06666667 ⋯ 0.00000000 0.00000000
[43,] 0       0.02380952 0.00000000 0.00000000 ⋯ 0.02380952 0.00000000
[44,] 0       0.00000000 0.00000000 0.02777778 ⋯ 0.05555556 0.00000000
[45,] 0       0.00000000 0.00000000 0.00000000 ⋯ 0.00000000 0.00000000
[46,] 0       0.00000000 0.00000000 0.00000000 ⋯ 0.03125000 0.00000000
[47,] 0       0.00000000 0.02272727 0.00000000 ⋯ 0.02272727 0.00000000
[48,] 0       0.00000000 0.00000000 0.00000000 ⋯ 0.02040816 0.00000000
[49,] 0       0.00000000 0.00000000 0.00000000 ⋯ 0.00000000 0.05555556
[50,] 0       0.00000000 0.00000000 0.00000000 ⋯ 0.00000000 0.00000000
[51,] 0       0.00000000 0.00000000 0.00000000 ⋯ 0.00000000 0.00000000
[52,] 0       0.00000000 0.00000000 0.02127660 ⋯ 0.00000000 0.00000000
[53,] 0       0.00000000 0.00000000 0.00000000 ⋯ 0.00000000 0.02325581
[54,] 0       0.00000000 0.00000000 0.00000000 ⋯ 0.02500000 0.00000000
[55,] 0       0.00000000 0.00000000 0.02380952 ⋯ 0.00000000 0.00000000
[56,] 0       0.03571429 0.00000000 0.00000000 ⋯ 0.00000000 0.00000000
[57,] 0       0.00000000 0.00000000 0.00000000 ⋯ 0.00000000 0.00000000
[58,] 0       0.00000000 0.02500000 0.00000000 ⋯ 0.00000000 0.00000000
[59,] 0       0.00000000 0.00000000 0.00000000 ⋯ 0.05555556 0.00000000
[60,] 0       0.00000000 0.00000000 0.00000000 ⋯ 0.00000000 0.02222222
[61,] 0       0.00000000 0.00000000 0.00000000 ⋯ 0.00000000 0.02173913
      MV         FV         PV         SV         TV         WV YV
 [1,] 0          0.00000    0.00000000 0          0          0  0.00000000
 [2,] 0          0.00000    0.00000000 0          0          0  0.00000000
 [3,] 0          0.00000    0.00000000 0          0          0  0.03225806
 [4,] 0          0.00000    0.00000000 0          0          0  0.00000000
 [5,] 0          0.00000    0.00000000 0          0          0  0.00000000
 [6,] 0          0.00000    0.03333333 0          0          0  0.00000000
 [7,] 0          0.00000    0.00000000 0          0          0  0.00000000
 [8,] 0          0.00000    0.00000000 0          0          0  0.00000000
 [9,] 0          0.00000    0.00000000 0          0          0  0.00000000
[10,] 0          0.00000    0.00000000 0          0          0  0.00000000
[11,] 0          0.00000    0.00000000 0          0          0  0.00000000
[12,] 0          0.00000    0.02040816 0          0          0  0.00000000
[13,] 0          0.00000    0.00000000 0          0          0  0.00000000
[14,] 0          0.00000    0.00000000 0          0          0  0.00000000
[15,] 0          0.00000    0.00000000 0          0          0  0.00000000
[16,] 0          0.00000    0.00000000 0          0          0  0.00000000
[17,] 0          0.00000    0.00000000 0          0          0  0.00000000
[18,] 0          0.00000    0.00000000 0          0          0  0.00000000
[19,] 0          0.00000    0.03333333 0          0          0  0.00000000
[20,] 0          0.00000    0.00000000 0          0          0  0.00000000
[21,] 0          0.00000    0.00000000 0          0          0  0.00000000
[22,] 0          0.03125    0.03125000 0          0          0  0.00000000
[23,] 0          0.00000    0.00000000 0          0          0  0.00000000
[24,] 0          0.00000    0.00000000 0          0          0  0.00000000
[25,] 0          0.00000    0.05263158 0          0          0  0.00000000
[26,] 0          0.00000    0.00000000 0          0          0  0.00000000
[27,] 0          0.00000    0.00000000 0          0          0  0.00000000
[28,] 0          0.00000    0.00000000 0          0          0  0.00000000
[29,] 0          0.00000    0.00000000 0          0          0  0.00000000
[30,] 0          0.00000    0.00000000 0          0          0  0.00000000
[31,] ⋮          ⋮          ⋮          ⋮          ⋮          ⋮  ⋮
[32,] 0.00000000 0.00000000 0.000      0.00000000 0.00000000 0  0.00000000
[33,] 0.00000000 0.00000000 0.000      0.00000000 0.00000000 0  0.00000000
[34,] 0.00000000 0.00000000 0.000      0.00000000 0.00000000 0  0.00000000
[35,] 0.00000000 0.00000000 0.000      0.00000000 0.00000000 0  0.00000000
[36,] 0.00000000 0.00000000 0.000      0.02040816 0.00000000 0  0.02040816
[37,] 0.00000000 0.00000000 0.000      0.00000000 0.00000000 0  0.00000000
[38,] 0.00000000 0.00000000 0.025      0.00000000 0.00000000 0  0.00000000
[39,] 0.00000000 0.04878049 0.000      0.00000000 0.00000000 0  0.00000000
[40,] 0.00000000 0.00000000 0.000      0.00000000 0.00000000 0  0.00000000
[41,] 0.00000000 0.00000000 0.000      0.00000000 0.00000000 0  0.00000000
[42,] 0.00000000 0.00000000 0.000      0.00000000 0.00000000 0  0.00000000
[43,] 0.00000000 0.00000000 0.000      0.02380952 0.00000000 0  0.00000000
[44,] 0.00000000 0.02777778 0.000      0.00000000 0.00000000 0  0.00000000
[45,] 0.00000000 0.00000000 0.000      0.00000000 0.00000000 0  0.00000000
[46,] 0.00000000 0.03125000 0.000      0.00000000 0.00000000 0  0.00000000
[47,] 0.00000000 0.00000000 0.000      0.00000000 0.00000000 0  0.00000000
[48,] 0.02040816 0.00000000 0.000      0.00000000 0.00000000 0  0.02040816
[49,] 0.02777778 0.00000000 0.000      0.02777778 0.00000000 0  0.00000000
[50,] 0.00000000 0.00000000 0.000      0.00000000 0.00000000 0  0.00000000
[51,] 0.00000000 0.00000000 0.000      0.00000000 0.00000000 0  0.00000000
[52,] 0.00000000 0.02127660 0.000      0.02127660 0.00000000 0  0.00000000
[53,] 0.00000000 0.00000000 0.000      0.02325581 0.00000000 0  0.00000000
[54,] 0.00000000 0.00000000 0.000      0.00000000 0.00000000 0  0.00000000
[55,] 0.00000000 0.00000000 0.000      0.02380952 0.02380952 0  0.00000000
[56,] 0.00000000 0.00000000 0.000      0.03571429 0.00000000 0  0.00000000
[57,] 0.00000000 0.00000000 0.000      0.00000000 0.00000000 0  0.00000000
[58,] 0.00000000 0.00000000 0.000      0.00000000 0.05000000 0  0.00000000
[59,] 0.00000000 0.00000000 0.000      0.00000000 0.00000000 0  0.00000000
[60,] 0.00000000 0.00000000 0.000      0.00000000 0.00000000 0  0.02222222
[61,] 0.00000000 0.00000000 0.000      0.00000000 0.00000000 0  0.00000000
      VV
 [1,] 0.00000000
 [2,] 0.00000000
 [3,] 0.00000000
 [4,] 0.02941176
 [5,] 0.00000000
 [6,] 0.00000000
 [7,] 0.00000000
 [8,] 0.00000000
 [9,] 0.05555556
[10,] 0.00000000
[11,] 0.00000000
[12,] 0.00000000
[13,] 0.00000000
[14,] 0.05555556
[15,] 0.00000000
[16,] 0.00000000
[17,] 0.00000000
[18,] 0.00000000
[19,] 0.00000000
[20,] 0.00000000
[21,] 0.00000000
[22,] 0.00000000
[23,] 0.00000000
[24,] 0.00000000
[25,] 0.00000000
[26,] 0.00000000
[27,] 0.00000000
[28,] 0.00000000
[29,] 0.00000000
[30,] 0.00000000
[31,] ⋮
[32,] 0.00000000
[33,] 0.00000000
[34,] 0.00000000
[35,] 0.00000000
[36,] 0.00000000
[37,] 0.00000000
[38,] 0.00000000
[39,] 0.00000000
[40,] 0.00000000
[41,] 0.00000000
[42,] 0.00000000
[43,] 0.00000000
[44,] 0.00000000
[45,] 0.00000000
[46,] 0.03125000
[47,] 0.00000000
[48,] 0.00000000
[49,] 0.00000000
[50,] 0.00000000
[51,] 0.00000000
[52,] 0.00000000
[53,] 0.00000000
[54,] 0.00000000
[55,] 0.00000000
[56,] 0.00000000
[57,] 0.00000000
[58,] 0.00000000
[59,] 0.00000000
[60,] 0.02222222
[61,] 0.00000000

In [ ]:
write.csv(x2,"/content/dcdata.csv")

In [ ]:
seq = "AKAAYIKQSAHNVIE"            ### for AA : total = 14, (AA counts as 1) 1/14 = 0.07142857
#seq = "EDDHHHHHHHHHGVGGGGGGGGGG"
dd_seq = extractDC(seq)            ### for IK : total = 14, (IK counts as 1) 1/14 = 0.07142857

In [ ]:
dd_seq

        AA         RA         NA         DA         CA         EA         QA
0.07142857 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        GA         HA         IA         LA         KA         MA         FA
0.00000000 0.00000000 0.00000000 0.00000000 0.07142857 0.00000000 0.00000000
        PA         SA         TA         WA         YA         VA         AR
0.00000000 0.07142857 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        RR         NR         DR         CR         ER         QR         GR
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        HR         IR         LR         KR         MR         FR         PR
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        SR         TR         WR         YR         VR         AN         RN
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        NN         DN         CN         EN         QN         GN         HN
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.07142857
        IN         LN         KN         MN         FN         PN         SN
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        TN         WN         YN         VN         AD         RD         ND
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        DD         CD         ED         QD         GD         HD         ID
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        LD         KD         MD         FD         PD         SD         TD
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        WD         YD         VD         AC         RC         NC         DC
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        CC         EC         QC         GC         HC         IC         LC
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        KC         MC         FC         PC         SC         TC         WC
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        YC         VC         AE         RE         NE         DE         CE
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        EE         QE         GE         HE         IE         LE         KE
0.00000000 0.00000000 0.00000000 0.00000000 0.07142857 0.00000000 0.00000000
        ME         FE         PE         SE         TE         WE         YE
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        VE         AQ         RQ         NQ         DQ         CQ         EQ
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        QQ         GQ         HQ         IQ         LQ         KQ         MQ
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.07142857 0.00000000
        FQ         PQ         SQ         TQ         WQ         YQ         VQ
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        AG         RG         NG         DG         CG         EG         QG
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        GG         HG         IG         LG         KG         MG         FG
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        PG         SG         TG         WG         YG         VG         AH
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.07142857
        RH         NH         DH         CH         EH         QH         GH
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        HH         IH         LH         KH         MH         FH         PH
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        SH         TH         WH         YH         VH         AI         RI
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        NI         DI         CI         EI         QI         GI         HI
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        II         LI         KI         MI         FI         PI         SI
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        TI         WI         YI         VI         AL         RL         NL
0.00000000 0.00000000 0.07142857 0.07142857 0.00000000 0.00000000 0.00000000
        DL         CL         EL         QL         GL         HL         IL
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        LL         KL         ML         FL         PL         SL         TL
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        WL         YL         VL         AK         RK         NK         DK
0.00000000 0.00000000 0.00000000 0.07142857 0.00000000 0.00000000 0.00000000
        CK         EK         QK         GK         HK         IK         LK
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.07142857 0.00000000
        KK         MK         FK         PK         SK         TK         WK
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        YK         VK         AM         RM         NM         DM         CM
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        EM         QM         GM         HM         IM         LM         KM
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        MM         FM         PM         SM         TM         WM         YM
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        VM         AF         RF         NF         DF         CF         EF
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        QF         GF         HF         IF         LF         KF         MF
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        FF         PF         SF         TF         WF         YF         VF
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        AP         RP         NP         DP         CP         EP         QP
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        GP         HP         IP         LP         KP         MP         FP
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        PP         SP         TP         WP         YP         VP         AS
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        RS         NS         DS         CS         ES         QS         GS
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.07142857 0.00000000
        HS         IS         LS         KS         MS         FS         PS
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        SS         TS         WS         YS         VS         AT         RT
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        NT         DT         CT         ET         QT         GT         HT
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        IT         LT         KT         MT         FT         PT         ST
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        TT         WT         YT         VT         AW         RW         NW
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        DW         CW         EW         QW         GW         HW         IW
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        LW         KW         MW         FW         PW         SW         TW
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        WW         YW         VW         AY         RY         NY         DY
0.00000000 0.00000000 0.00000000 0.07142857 0.00000000 0.00000000 0.00000000
        CY         EY         QY         GY         HY         IY         LY
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        KY         MY         FY         PY         SY         TY         WY
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        YY         VY         AV         RV         NV         DV         CV
0.00000000 0.00000000 0.00000000 0.00000000 0.07142857 0.00000000 0.00000000
        EV         QV         GV         HV         IV         LV         KV
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        MV         FV         PV         SV         TV         WV         YV
0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
        VV
0.00000000

In [ ]:
typeof(dd_seq)

[1] "double"